// This file is automatically generated. DO NOT EDIT.

/* eslint-disable */

export const PACKAGE_INFO = {
  "name": "@ncoderz/awa",
  "version": "1.5.0",
  "author": "Richard Sewell <richard.sewell@ncoderz.com>",
  "license": "MIT",
  "description": "awa is an Agent Workflow for AIs. It is also a CLI tool to powerfully manage agent workflow files using templates."
};
