/**
 * Extract the build info from the package.json file
 * and write it to a TypeScript file.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import pkg from '../package.json' with { type: 'json' };

async function createPackageInfo(_rootDir: URL, srcDir: URL): Promise<void> {
  const PACKAGE_INFO = {
    name: pkg.name ?? '',
    version: pkg.version ?? '',
    author: pkg.author ?? '',
    license: pkg.license ?? '',
    description: pkg.description ?? '',
  };

  const buildInfoFileContent = `// This file is automatically generated. DO NOT EDIT.

/* eslint-disable */

export const PACKAGE_INFO = ${JSON.stringify(PACKAGE_INFO, null, 2)};
`;

  const buildInfoPath = path.join(fileURLToPath(srcDir), 'package_info.ts');
  await fs.writeFile(buildInfoPath, buildInfoFileContent, 'utf8');
}

export { createPackageInfo };
